### ISSUE TITLE
host does not support IPv6 addr.

### ISSUE THREAD

**Issue by limitcool** [Corsinvest/cv4pve-pepper#34]
ERROR: One or more errors occurred.

**Comment by franklupo** [comment]
Hi,
Can you explain better?

best regards

**Comment by limitcool** [comment]
``` bash
cv4pve-pepper --host [*]:8006 --viewer pve.vv --api-token *
```
I used ipv6 addr as the parameter for the host, and the above error was returned.
``` text
ERROR: One or more errors occurred.
```

**Comment by franklupo** [comment]
> ```shell
> cv4pve-pepper --host [*]:8006 --viewer pve.vv --api-token *
> ```
> 
> I used ipv6 addr as the parameter for the host, and the above error was returned.
> 
> ```
> ERROR: One or more errors occurred.
> ```

you can run with --debug and attach the logo. Be careful that it also contains the passwords in clear.

**Comment by limitcool** [comment]
```
ERROR: One or more errors occurred. (No such host is known.)
ERROR: No such host is known.
================ EXCEPTION ================
System.AggregateException
One or more errors occurred. (No such host is known.)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at Corsinvest.ProxmoxVE.Api.Extension.Utils.ClientHelper.TryHostAndPort(String hostsAndPorts, Int32 defaultPort, Boolean checkPort, Int32 timeout, String& host, Int32& port)
   at Corsinvest.ProxmoxVE.Api.Extension.Utils.ClientHelper.GetClientFromHA(String hostsAndPortHA, Int32 timeout)
   at Corsinvest.ProxmoxVE.Api.Extension.Utils.ClientHelper.GetClientAndTryLoginAsync(String hostsAndPortHA, String username, String password, String apiToken, Boolean validateCertificate, ILoggerFactory loggerFactory, Int32 timeout)
   at Corsinvest.ProxmoxVE.Api.Shell.Helpers.CommandOptionExtension.ClientTryLoginAsync(Command command, ILoggerFactory loggerFactory)
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
fail: Program[0]
      One or more errors occurred. (No such host is known.)
      System.AggregateException: One or more errors occurred. (No such host is known.)
       ---> System.Net.Sockets.SocketException (11001): No such host is known.
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
      --- End of stack trace from previous location ---
         at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
         at Corsinvest.ProxmoxVE.Api.Extension.Utils.ClientHelper.TryHostAndPort(String hostsAndPorts, Int32 defaultPort, Boolean checkPort, Int32 timeout, String& host, Int32& port)
         at Corsinvest.ProxmoxVE.Api.Extension.Utils.ClientHelper.GetClientFromHA(String hostsAndPortHA, Int32 timeout)
         at Corsinvest.ProxmoxVE.Api.Extension.Utils.ClientHelper.GetClientAndTryLoginAsync(String hostsAndPortHA, String username, String password, String apiToken, Boolean validateCertificate, ILoggerFactory loggerFactory, Int32 timeout)
         at Corsinvest.ProxmoxVE.Api.Shell.Helpers.CommandOptionExtension.ClientTryLoginAsync(Command command, ILoggerFactory loggerFactory)
         at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
         at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
      --- End of stack trace
```

**Comment by franklupo** [comment]
Hi,
but `[*]` is not a valid ip or dns.

**Comment by limitcool** [comment]
The content indicated by [*] is the IPv6 address: [2001:0db8:85a3:0000:0000:8a2e:0370:7334]

**Comment by franklupo** [comment]
Ping work?

**Comment by limitcool** [comment]
> Ping work?

Yes, I can access my Proxmox VE backend via the web interface, but I'm unable to access it using cv4pve-pepper.
[2001:0db8:85a3:0000:0000:8a2e:0370:7334]" is a randomly generated IPv6 address; I'm just showing you the format I'm using. I'm confident that the actual IPv6 address I'm using is valid. I've tried accessing it with "http://[********]", but that didn't work either.

**Comment by franklupo** [comment]
Are you using cv4pve-pepper outside of Proxmox?
