### ISSUE TITLE
Raspberry PI running Buster Exception

### ISSUE THREAD

**Issue by johnplagis** [Corsinvest/cv4pve-pepper#4]
On a Raspberry PI 3 running the latest version of Raspberry OS (Buster), and using the ARM version of cv4pve-pepper when I run the following command: 

`./cv4pve-pepper --host=192.168.1.2 --username=root --password=testPassw0rd --vmid 104 --viewer /usr/bin/virt-viewer`

I get the following exception:

`================ EXCEPTION ================ 
System.ComponentModel.Win32Exception
No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Corsinvest.ProxmoxVE.Pepper.Program.<>c__DisplayClass0_0.<Main>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass144_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Corsinvest.ProxmoxVE.Api.Shell.Helpers.ShellHelper.ExecuteConsoleApp(CommandLineApplication app, String[] args)`

**Comment by franklupo** [comment]
Hi,
which version do you use?
--version show version

best regards

**Comment by johnplagis** [comment]
Hello, I am using the latest version (I haven't tried any of the versions before that, should I?):
`
Launching SPICE on Proxmox VE                  (Made in Italy)
1.3.0
`
