### ISSUE TITLE
Error: Unknown Host

### ISSUE THREAD

**Issue by MiningPickaxe** [Corsinvest/cv4pve-pepper#9]
Hello,

I'm trying to launch cv4pve-pepper 1.3.7 with `./cv4pve-pepper --host=80.XXX.XXX.XXX:8006 --username=XXXX@XXXX --password=XXXX --vmid=124 --viewer=/usr/bin/virt-viewer` and also tried it without specifying the port. 
All I get is the following Error:
```
Error: unknown host 80.XXX.XXX.XXX
Problem connection!
```
with the `--debug` flag I get the following:
```
================ EXCEPTION ================ 
System.ApplicationException
Problem connection!
   at Corsinvest.ProxmoxVE.Api.Shell.Helpers.CommandOptionExtension.ClientTryLogin(CommandLineApplication command)
   at Corsinvest.ProxmoxVE.Pepper.Program.<>c__DisplayClass0_0.<Main>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass144_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Corsinvest.ProxmoxVE.Api.Shell.Helpers.ShellHelper.ExecuteConsoleApp(CommandLineApplication app, String[] args)
```
I can open the Web GUI just fine with that URL. What am I missin?

**Comment by franklupo** [comment]
Hi,
try with --proxy=80.XXX.XXX.XXX.
The firewal is enabled?

**Comment by MiningPickaxe** [comment]
Hi, returns the same error with the --proxy
The firewall of Proxmox is not enabled, however there is a firewall in front of the network. But I successfully managed to run pepper a few weeks ago while I was still in office, now at home on a different computer it won't work anymore. Both computers should be in the same network, thats why I suspect the firewall is not the issue.

**Comment by franklupo** [comment]
Try with old version.

**Comment by MiningPickaxe** [comment]
Tried it with 1.3.3 now, still get the same error. The error message doesn't really tell what went wrong :/

**Comment by franklupo** [comment]
Test new version. I imporve the log. Use the parameter --debug and attach me result. 

Bets regards

**Comment by MiningPickaxe** [comment]
Error: unknown host 80.XXX.XXX.XXX
Problem connection!
================ EXCEPTION ================ 
System.ApplicationException
Problem connection!
   at Corsinvest.ProxmoxVE.Api.Shell.Helpers.CommandOptionExtension.ClientTryLogin(CommandLineApplication command)
   at Corsinvest.ProxmoxVE.Pepper.Program.<>c__DisplayClass0_0.<Main>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass144_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Corsinvest.ProxmoxVE.Api.Shell.Helpers.ShellHelper.ExecuteConsoleApp(CommandLineApplication app, String[] args)

**Comment by franklupo** [comment]
Hi,
Ping work?

**Comment by franklupo** [comment]
News?

**Comment by codiflow** [comment]
Just try with `sudo` in front. This gave me a more detailed log output.
